const allProducts = [
    {
      id: 1,
      name: "Smartphone X",
      price: 799.99,
      rating: 4.5,
      category: "Electronics",
      image: "/TheBand-SmartPhone.jpg",
      description: "A high-end smartphone with advanced features.",
      numberOfRatings: 20,
    },
    {
      id: 2,
      name: "Laptop Pro",
      price: 1299.99,
      rating: 4.7,
      category: "Electronics",
      image: "/TheBand-Laptop.jpg",
      description: "Powerful laptop for professionals and gamers.",
      numberOfRatings: 15,
    },
    {
      id: 3,
      name: "Wireless Headphones",
      price: 199.99,
      rating: 4.3,
      category: "Electronics",
      image: "/TheBand-HeadPhones.jpg",
      description: "Noise-cancelling headphones with long battery life.",
      numberOfRatings: 30,
    },
    {
      id: 4,
      name: "Men's T-Shirt",
      price: 29.99,
      rating: 4.0,
      category: "Clothing",
      image: "/TheBand-MenTshirt.jpg",
      description: "Comfortable and stylish t-shirt for men.",
      numberOfRatings: 25,
    },
    {
      id: 5,
      name: "Women's Dress",
      price: 59.99,
      rating: 4.2,
      category: "Clothing",
      image: "/TheBand-WomenDress.jpg",
      description: "Elegant dress for women, perfect for any occasion.",
      numberOfRatings: 18,
    },
    {
      id: 6,
      name: "Leather Wallet",
      price: 49.99,
      rating: 4.4,
      category: "Accessories",
      image: "/TheBand-Wallet.jpg",
      description: "Premium leather wallet with multiple compartments.",
      numberOfRatings: 22,
    },
    {
      id: 7,
      name: "Smart Watch",
      price: 249.99,
      rating: 4.6,
      category: "Electronics",
      image: "/TheBand-SmartWatch.jpg",
      description: "Smartwatch with fitness tracking and notifications.",
      numberOfRatings: 28,
    },
    {
      id: 8,
      name: "Sunglasses",
      price: 99.99,
      rating: 4.1,
      category: "Accessories",
      image: "/TheBand-Sunglasses.jpg",
      description: "Stylish sunglasses with UV protection.",
      numberOfRatings: 12,
    },
  ];

  export default allProducts;